# Generated by Django 4.2.13 on 2024-06-21 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('contenue', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ManyToManyField(blank=True, null=True, to='Institution.classe')),
            ],
        ),
    ]
