# Generated by Django 4.2.13 on 2024-05-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institution', '0001_initial'),
        ('Communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='classe',
            field=models.ManyToManyField(blank=True, null=True, to='Institution.classe'),
        ),
    ]
