# Generated by Django 4.2.13 on 2024-05-26 10:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institution', '0002_initial'),
        ('Utilisateurs', '0002_table_eleve_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('classe', models.ManyToManyField(blank=True, related_name='cours', to='Institution.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='Institution.classe')),
                ('cour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='Taches.cour')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='Utilisateurs.table_eleve')),
            ],
        ),
        migrations.CreateModel(
            name='devoir_soumission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='Utilisateurs.table_eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='devoir/')),
                ('classe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Institution.classe')),
                ('cour', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Taches.cour')),
            ],
        ),
    ]
