# Generated by Django 4.2.13 on 2024-06-21 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateurs', '0001_initial'),
        ('Institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institution.classe')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.table_eleve')),
            ],
        ),
    ]
