# Generated by Django 4.2.13 on 2024-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_eleve',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='table_eleve',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
