# Generated by Django 4.2.13 on 2024-06-21 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.SmallIntegerField(choices=[(1, 'approuver'), (0, 'no approuver')], default=1)),
                ('frais_scolaire_choice', models.CharField(choices=[('frais scolaire trimestre 1', 'frais scolaire trimestre 1'), ('frais scolaire trimestre 2', 'frais scolaire trimestre 2'), ('frais scolaire trimestre 3', 'frais scolaire trimestre 3')], max_length=50)),
                ('montants', models.IntegerField(blank=True, default=0, null=True)),
                ('document', models.FileField(default=None, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='Utilisateurs.table_eleve')),
            ],
        ),
    ]
